require("dotenv").config();
const express=require("express"), path=require("path"), OpenAI=require("openai");
const app=express(); app.use(express.json({limit:"50kb"})); app.use(express.static(path.join(__dirname,"public")));
const client=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const clinic={name:"ABC Dental Clinic",city:"Bengaluru",address:"123 Main Road, Bengaluru (demo)",hours:"Monday–Saturday, 10:00 AM–7:00 PM. Sunday: closed.",phone:"+91 90000 00000 (demo)",services:["Dental consultation","Teeth cleaning","Fillings","Root-canal consultation","Crowns and bridges","Orthodontic consultation"],fees:{consultation:"₹500",cleaning:"₹1,000"}};
const instructions=`You are DentalLead, the administrative AI receptionist for ${clinic.name}.
Clinic: ${clinic.name}; City: ${clinic.city}; Address: ${clinic.address}; Hours: ${clinic.hours}; Phone: ${clinic.phone}; Services: ${clinic.services.join(", ")}; Approved fees: consultation ${clinic.fees.consultation}, cleaning ${clinic.fees.cleaning}.
Rules: Be warm, concise and professional. Never diagnose, prescribe/recommend medication, invent facts, prices, availability or policies. If clinical judgment is needed, say a dentist must assess the patient and offer an appointment request. For severe pain, major swelling, uncontrolled bleeding, breathing difficulty or serious injury, advise contacting the clinic or seeking urgent appropriate care; do not diagnose. Collect only name, preferred day/time and requested service for appointment requests. Never claim a booking is confirmed; this demo only creates an appointment request. Do not ask for unnecessary medical history or sensitive information.`;
app.post("/api/chat",async(req,res)=>{try{if(!client)return res.status(503).json({error:"OPENAI_API_KEY is not configured."});let ms=(req.body.messages||[]).slice(-12).filter(x=>x&&(x.role==="user"||x.role==="assistant")&&typeof x.content==="string");let r=await client.responses.create({model:"gpt-5.4-mini",instructions,input:ms.map(x=>({role:x.role,content:x.content})),max_output_tokens:350});res.json({reply:r.output_text});}catch(e){console.error(e);res.status(500).json({error:"AI request failed."})}});
app.get("/api/health",(_,res)=>res.json({ok:true}));
app.listen(process.env.PORT||3000,()=>console.log("DentalLead: http://localhost:"+(process.env.PORT||3000)));
